export const SIGNIN = 'SIGNIN'
export const SIGNIN_ASYNC = 'SIGNIN_ASYNC'
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
export const UPDATE_LANGUAGE_ASYNC = `${UPDATE_LANGUAGE}_ASYNC`
export const UPDATE_NOTIFICATION_TOKEN = 'UPDATE_NOTIFICATION_TOKEN'
export const UPDATE_NOTIFICATION_TOKEN_ASYNC = 'UPDATE_NOTIFICATION_TOKEN_ASYNC'
