export const GET_CURRENCIES = 'GET_CURRENCIES'
export const GET_CURRENCIES_ASYNC = 'GET_CURRENCIES_ASYNC'
export const GET_CURRENCY_PRICE = 'GET_CURRENCY_PRICE'
export const GET_CURRENCY_PRICE_ASYNC = `${GET_CURRENCY_PRICE}_ASYNC`
export const GET_CRYPTO_CURRENCIES = 'GET_CRYPTO_CURRENCIES'
export const GET_CRYPTO_CURRENCIES_ASYNC = `${GET_CRYPTO_CURRENCIES}_ASYNC`
