export const CREATE_OUTCOME = 'CREATE_OUTCOME'
export const CREATE_OUTCOME_ASYNC = `${CREATE_OUTCOME}_ASYNC`

export const GET_OUTCOMES = 'GET_OUTCOMES'
export const GET_OUTCOMES_ASYNC = `${GET_OUTCOMES}_ASYNC`

export const CREATE_OUTCOME_CATEGORY = 'CREATE_OUTCOME_CATEGORY'
export const CREATE_OUTCOME_CATEGORY_ASYNC = `${CREATE_OUTCOME_CATEGORY}_ASYNC`

export const CREATE_BASIC_EXPENSES = 'CREATE_BASIC_EXPENSES'
export const CREATE_BASIC_EXPENSES_ASYNC = `${CREATE_BASIC_EXPENSES}_ASYNC`

export const GET_BASIC_EXPENSES = 'GET_BASIC_EXPENSES'
export const GET_BASIC_EXPENSES_ASYNC = `${GET_BASIC_EXPENSES}_ASYNC`

export const GET_BASIC_EXPENSE = 'GET_BASIC_EXPENSE'
export const GET_BASIC_EXPENSE_ASYNC = `${GET_BASIC_EXPENSE}_ASYNC`

export const REMOVE_EXPENSE_ITEM = 'REMOVE_EXPENSE_ITEM'

export const UPDATE_BASIC_EXPENSE = 'UPDATE_BASIC_EXPENSE'
export const UPDATE_BASIC_EXPENSE_ASYNC = `${UPDATE_BASIC_EXPENSE}_ASYNC`

export const DELETE_OUTCOME = 'DELETE_OUTCOME'
export const DELETE_OUTCOME_ASYNC = `${DELETE_OUTCOME}_ASYNC`

export const GET_CATEGORY_OUTCOME = 'GET_CATEGORY_OUTCOME'
export const GET_CATEGORY_OUTCOME_ASYNC = `${GET_CATEGORY_OUTCOME}_ASYNC`

export const UPDATE_CATEGORY_OUTCOME = 'UPDATE_CATEGORY_OUTCOME'
export const UPDATE_CATEGORY_OUTCOME_ASYNC = `${UPDATE_CATEGORY_OUTCOME}_ASYNC`

export const DELETE_CATEGORY_OUTCOME = 'DELETE_CATEGORY_OUTCOME'
export const DELETE_CATEGORY_OUTCOME_ASYNC = `${DELETE_CATEGORY_OUTCOME}_ASYNC`

export const CREATE_DEBT = 'CREATE_DEBT'
export const CREATE_DEBT_ASYNC = `${CREATE_DEBT}_ASYNC`

export const GET_DEBTS = 'GET_DEBTS'
export const GET_DEBTS_ASYNC = `${GET_DEBTS}_ASYNC`

export const GET_DEBT = 'GET_DEBT'
export const GET_DEBT_ASYNC = `${GET_DEBT}_ASYNC`

export const UPDATE_DEBT = 'UPDATE_DEBT'
export const UPDATE_DEBT_ASYNC = `${UPDATE_DEBT}_ASYNC`

export const DELETE_DEBT = 'DELETE_DEBT'
export const DELETE_DEBT_ASYNC = `${DELETE_DEBT}_ASYNC`

export const CREATE_DEBT_ENTRY = 'CREATE_DEBT_ENTRY'
export const CREATE_DEBT_ENTRY_ASYNC = `${CREATE_DEBT_ENTRY}_ASYNC`
