import { Platform } from "react-native"

export const egressForm = (translate: any, def: any, colors: any = {}) => [
  {
    element: 'input',
    name: 'concept',
    label: translate('concept'),
    labelStyle: {backgroundColor: colors?.background100},
    type: 'text',
    defaultValue: def?.concept?.value || '',
    placeholder: translate('concept'),
    returnKeyType: 'next',
    keyboardType: 'default',
    validations: {
      required: true,
      minLength: 0,
      maxLength: 72,
    },
  },
  {
    element: 'input',
    name: 'comment',
    label: translate('comments_optional'),
    labelStyle: {backgroundColor: colors?.background100},
    type: 'text',
    defaultValue: def?.comment?.value || '',
    placeholder: translate('comments'),
    returnKeyType: 'next',
    keyboardType: 'default',
    validations: {
      required: false,
      minLength: 0,
      maxLength: 72,
    },
  },
  {
    element: 'input',
    name: 'amount',
    label: translate('amount'),
    labelStyle: {backgroundColor: colors?.background100},
    type: 'text',
    defaultValue: def?.amount?.value || '',
    placeholder: translate('amount'),
    returnKeyType: 'next',
    keyboardType: 'numeric',
    validations: {
      required: true,
      minLength: 0,
      maxLength: 72,
    },
  },
  {
    element: 'date',
    name: 'date',
    label: translate('next_payment_date'),
    labelStyle: {backgroundColor: colors?.background100},
    date: def?.date?.value || new Date(),
    placeholder: translate('date'),
    validations: {
      required: true,
    },
  },
  {
    element: 'select',
    name: 'status_level',
    type: 'select',
    label: translate('urgency_level'),
    labelStyle: {backgroundColor: colors?.background100},
    defaultValue: def ? def.status_level?.value : '',
    placeholder: translate('urgency_level'),
    itemStyle:(Platform.OS === 'ios')? {color: colors.typography}:{},
    values: [
      {
        value: 'low',
        label: translate('low'),
      },
      {
        value: 'medium',
        label: translate('medium'),
      },
      {
        value: 'high',
        label: translate('high'),
      },
    ],
    validations: {
      required: true,
    },
  },
  {
    element: 'date',
    name: 'limit_date',
    label: translate('limit_payment_date'),
    labelStyle: {backgroundColor: colors?.background100},
    date: def?.limit_date?.value || new Date(),
    placeholder: translate('date'),
    validations: {
      required: true,
    },
  },
]

export const receiverForm = (translate: any, def: any, colors: any = {}) => [
  {
    element: 'input',
    name: 'receiver_name',
    label: translate('receiver_name_optional'),
    labelStyle: {backgroundColor: colors?.background100},
    type: 'text',
    defaultValue: def?.receiver_name?.value || '',
    placeholder: translate('receiver_name'),
    returnKeyType: 'next',
    keyboardType: 'default',
    validations: {
      required: false,
      minLength: 0,
      maxLength: 72,
    },
  },
  {
    element: 'input',
    name: 'phonenumber',
    label: translate('phonenumber_optional'),
    labelStyle: {backgroundColor: colors?.background100},
    type: 'text',
    defaultValue: def?.phonenumber?.value || '',
    placeholder: translate('phonenumber'),
    returnKeyType: 'next',
    keyboardType: 'default',
    validations: {
      required: false,
      minLength: 0,
      maxLength: 72,
    },
  },
  {
    element: 'input',
    name: 'email',
    label: translate('email_optional'),
    labelStyle: {backgroundColor: colors?.background100},
    type: 'text',
    defaultValue: def?.email?.value || '',
    placeholder: translate('email'),
    returnKeyType: 'next',
    keyboardType: 'default',
    validations: {
      required: false,
      minLength: 0,
      maxLength: 72,
    },
  },
]
