export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION'
export const PUSH_NOTIFICATION_ASYNC = `${PUSH_NOTIFICATION}_ASYNC`
export const ALARM_NOTIFICATION = 'ALARM_NOTIFICATION'
export const SCHEDULE_NOTIFICATION = 'SCHEDULE_NOTIFICATION'
