export { default as FixedOutcome } from './FixedOutcome'
export { default as PendingOutcome } from './PendingOutcome'
export { default as MainGoals } from './MainGoals'
export { default as NewGoals } from './NewGoals'
export { default as DetailGoals } from './DetailGoals'
export { default as EditGoals } from './EditGoals'
export { default as DeleteGoals } from './DeleteGoals'