export {default as NewFixedIncome} from './NewFixedIncome'
export {default as MainFixesIncome} from './MainFixesIncome'
export {default as DetailFixesIncome} from './DetailFixesIncome'
export {default as EditFixedIncome} from './EditFixedIncome'
export {default as deleteIncome} from './DeleteIncome'
