export const CREATE_INCOME = 'CREATE_INCOME'
export const CREATE_INCOME_ASYNC = `${CREATE_INCOME}_ASYNC`

export const GET_INCOMES = 'GET_INCOMES'
export const GET_INCOMES_ASYNC = `${GET_INCOMES}_ASYNC`

export const CREATE_INCOME_CATEGORY = 'CREATE_INCOME_CATEGORY'
export const CREATE_INCOME_CATEGORY_ASYNC = `${CREATE_INCOME_CATEGORY}_ASYNC`

export const CREATE_FIXED_INCOMES = 'CREATE_FIXED_INCOMES'
export const CREATE_FIXED_INCOMES_ASYNC = `${CREATE_FIXED_INCOMES}_ASYNC`

export const CREATE_FIXED_INCOMES_ENTRY = 'CREATE_FIXED_INCOMES_ENTRY'
export const CREATE_FIXED_INCOMES_ENTRY_ASYNC = `${CREATE_FIXED_INCOMES_ENTRY}_ASYNC`

export const GET_FIXED_INCOMES = 'GET_FIXED_INCOMES'
export const GET_FIXED_INCOMES_ASYNC = `${GET_FIXED_INCOMES}_ASYNC`

export const GET_FIXED_INCOME = 'GET_FIXED_INCOME'
export const GET_FIXED_INCOME_ASYNC = `${GET_FIXED_INCOME}_ASYNC`

export const REMOVE_INCOME_ITEM = 'REMOVE_INCOME_ITEM'

export const UPDATE_FIXED_INCOME = 'UPDATE_FIXED_INCOME'
export const UPDATE_FIXED_INCOME_ASYNC = `${UPDATE_FIXED_INCOME}_ASYNC`

export const DELETE_INCOME = 'DELETE_INCOME'
export const DELETE_INCOME_ASYNC = `${DELETE_INCOME}_ASYNC`

export const GET_CATEGORY_INCOME = 'GET_CATEGORY_INCOME'
export const GET_CATEGORY_INCOME_ASYNC = `${GET_CATEGORY_INCOME}_ASYNC`

export const UPDATE_CATEGORY_INCOME = 'UPDATE_CATEGORY_INCOME'
export const UPDATE_CATEGORY_INCOME_ASYNC = `${UPDATE_CATEGORY_INCOME}_ASYNC`

export const DELETE_CATEGORY_INCOME = 'DELETE_CATEGORY_INCOME'
export const DELETE_CATEGORY_INCOME_ASYNC = `${DELETE_CATEGORY_INCOME}_ASYNC`

export const CREATE_RECEIVABLE_ACCOUNT = 'CREATE_RECEIVABLE_ACCOUNT'
export const CREATE_RECEIVABLE_ACCOUNT_ASYNC = `${CREATE_RECEIVABLE_ACCOUNT}_ASYNC`

export const GET_RECEIVABLE_ACCOUNTS = 'GET_RECEIVABLE_ACCOUNTS'
export const GET_RECEIVABLE_ACCOUNTS_ASYNC = `${GET_RECEIVABLE_ACCOUNTS}_ASYNC`

export const GET_RECEIVABLE_ACCOUNT = 'GET_RECEIVABLE_ACCOUNT'
export const GET_RECEIVABLE_ACCOUNT_ASYNC = `${GET_RECEIVABLE_ACCOUNT}_ASYNC`

export const UPDATE_RECEIVABLE_ACCOUNT = 'UPDATE_RECEIVABLE_ACCOUNT'
export const UPDATE_RECEIVABLE_ACCOUNT_ASYNC = `${UPDATE_RECEIVABLE_ACCOUNT}_ASYNC`

export const DELETE_RECEIVABLE_ACCOUNT = 'DELETE_RECEIVABLE_ACCOUNT'
export const DELETE_RECEIVABLE_ACCOUNT_ASYNC = `${DELETE_RECEIVABLE_ACCOUNT}_ASYNC`

export const CREATE_RECEIVABLE_ACCOUNT_ENTRY = 'CREATE_RECEIVABLE_ACCOUNT_ENTRY'
export const CREATE_RECEIVABLE_ACCOUNT_ENTRY_ASYNC = `${CREATE_RECEIVABLE_ACCOUNT_ENTRY}_ASYNC`
