export const SET_INCOMING = 'SET_INCOMING'
export const SET_INCOMING_ASYNC = `${SET_INCOMING}_ASYNC`
export const GET_INCOMING = 'GET_INCOMING'
export const GET_INCOMING_ASYNC = `${GET_INCOMING}_ASYNC`
