export const GET_ENTRIES_GOALS = 'GET_ENTRIES_GOALS'
export const GET_ENTRIES_GOALS_ASYNC = `${GET_ENTRIES_GOALS}_ASYNC`

export const CREATE_GOALS = 'CREATE_GOALS'
export const CREATE_GOALS_ASYNC = `${CREATE_GOALS}_ASYNC`

export const CREATE_CATEGORY_GOALS = 'CREATE_CATEGORY_GOALS'
export const CREATE_CATEGORY_GOALS_ASYNC = `${CREATE_CATEGORY_GOALS}_ASYNC`

export const GET_GOAL = 'GET_GOAL'
export const GET_GOAL_ASYNC = `${GET_GOAL}_ASYNC`

export const GET_CATEGORY_GOAL = 'GET_CATEGORY_GOAL'
export const GET_CATEGORY_GOAL_ASYNC = `${GET_CATEGORY_GOAL}_ASYNC`

export const REMOVE_GOAL_ITEM = 'REMOVE_GOAL_ITEM'

export const CREATE_GOAL_ENTRY = 'CREATE_GOAL_ENTRY'
export const CREATE_GOAL_ENTRY_ASYNC = `${CREATE_GOAL_ENTRY}_ASYNC`

export const UPDATE_GOAL = 'UPDATE_GOAL'
export const UPDATE_GOAL_ASYNC = `${UPDATE_GOAL}_ASYNC`

export const UPDATE_CATEGORY_GOAL = 'UPDATE_CATEGORY_GOAL'
export const UPDATE_CATEGORY_GOAL_ASYNC = `${UPDATE_CATEGORY_GOAL}_ASYNC`

export const DELETE_GOAL = 'DELETE_GOAL'
export const DELETE_GOAL_ASYNC = `${DELETE_GOAL}_ASYNC`

export const DELETE_CATEGORY_GOAL = 'DELETE_CATEGORY_GOAL'
export const DELETE_CATEGORY_GOAL_ASYNC = `${DELETE_CATEGORY_GOAL}_ASYNC`